version: '3.7'
services:

  anki_sync_server:
    image: ${DOCKER_IMAGE:-anki-sync-server}:${DOCKER_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # - GIT_REPOSITORY_URL=${GIT_REPOSITORY_URL}
        # - GIT_BRANCH=${GIT_BRANCH}
        # - GIT_COMMIT_SHA=${GIT_COMMIT_SHA}
        # - GIT_COMMIT_SHORT_SHA=${GIT_COMMIT_SHORT_SHA}
        # - GIT_COMMIT_TAG=${GIT_COMMIT_TAG}
        # - GIT_DIRTY=${GIT_DIRTY}
        # - BUILD_USER_NAME=${BUILD_USER_NAME}
        # - BUILD_USER_EMAIL=${BUILD_USER_EMAIL}
        # - BUILD_DATE=${BUILD_DATE}
        - ANKISYNCD_PORT=${ANKISYNCD_PORT:-27701}
        - ANKISYNCD_BASE_URL=${ANKISYNCD_BASE_URL:-/sync/}
        - ANKISYNCD_BASE_MEDIA_URL=${ANKISYNCD_BASE_MEDIA_URL:-/msync/}
        - ANKISYNCD_AUTH_DB_PATH=${ANKISYNCD_AUTH_DB_PATH:-./auth.db}
        - ANKISYNCD_SESSION_DB_PATH=${ANKISYNCD_SESSION_DB_PATH:-./session.db}
        # Currently these are hardcoded
        # - ANKISYNCD_GIT_REPOSITORY_URL=https://github.com/ankicommunity/anki-sync-server
        # - ANKISYNCD_GIT_BRANCH=master
        # - ANKISYNCD_GIT_COMMIT_SHA
        # - ANKISYNCD_GIT_COMMIT_SHORT_SHA
        # - ANKISYNCD_GIT_COMMIT_TAG